---
- name: Configure Access
  hosts: access
  connection: local
  gather_facts: false
  roles:
    - access
  vars:
    cli:
        username: mike
        password: password1234
        authorize: yes
        auth_pass: false

    dellos_interface:
      range Gi1/0/1-15:
        desc: "User_Port"
        portmode: User
        primary: 150
        isolated: 151
        admin: up

      Gi1/0/16:
        desc: "WAP_Ports"
        portmode: AP
        ap_vlan: 998
        admin: up

      Te1/0/1:
        desc: "Uplink"
        portmode: Uplink
        trunked_vlans: "150,151,998,999"
        admin: up

      range Te1/0/2-4:
        desc: "Downlink"
        portmode: Downlink
        trunked_vlans: "150,151,998,999"
        admin: up


  tasks:
      - name: Configure User Interfaces
        dellos6_config:
          provider: "{{ cli }}"
        when: ansible_net_os_name == "dellos6"
        register: print_output
      - debug: var=print_output
