---
- name: Lan Health
  hosts: agg
  gather_facts: no
  connection: local

  vars:
    cli:
        username: 
        password:
        authorize: yes
        auth_pass: false

  tasks:
    - name: Check Interface Status
      dellos6_command:
        provider: "{{ cli }}"
        commands: show interface status | include WAP_Ports exclude Unkown
        wait_for: result[0] contains 1000
      register: printout
#      tags: interfaces
    - set_fact:
        intf: |
          {{printout.stdout_lines[0] |
            map('regex_search','^([A-Za-z]+[0-9./]+)') |
            list }}
        register: interface[]
        tags: intferface

    - name: Get LLDP Detail Neighbor
      dellos6_command:
        provider: "{{ cli }}"
        commands: show lldp remote-device detail interface {{ interface }}
